version: '3.8'
services:
  backend:
    build:
      context: ./backend/src
      dockerfile: Debug.Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"  # For HTTPS if needed
    volumes:
      - ./backend:/app
      - backend-packages:/root/.nuget/packages  # Persist NuGet packages
    environment:
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - AppSettings__ConnectionStrings__DefaultConnection=Host=${POSTGRES_HOST};Port=${POSTGRES_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - AppSettings__Secret=${JWT_SECRET}
      - AppSettings__Issuer=${JWT_ISSUER}
      - AppSettings__Audience=${JWT_AUDIENCE}
      - AppSettings__PasswordResetUrl=${PASSWORD_RESET_URL}
      - SmtpSettings__SmtpServer=${SMTP_SERVER}
      - SmtpSettings__Port=${SMTP_PORT}
      - SmtpSettings__Username=${SMTP_USERNAME}
      - SmtpSettings__Password=${SMTP_PASSWORD}
      - SmtpSettings__FromEmail=${SMTP_FROM_EMAIL}
      - SmtpSettings__EnableSsl=${SMTP_ENABLE_SSL}
    depends_on:
      - postgres
    command: dotnet watch run --project Contact.Api/Contact.Api.csproj

  frontend:
    build:
      context: ./frontend
      dockerfile: Debug.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend-packages:/app/node_modules
    command: npm run serve
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=contacts_admin
      - POSTGRES_PASSWORD=YourStrongPassword123!
      - POSTGRES_DB=contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  backend-packages:  # Persist NuGet packages
  frontend-packages:  # Persist node_modules
