version: '3.8'
services:
 backend:
   build:
     context: ./backend/src
     dockerfile: Debug.Dockerfile
   command: dotnet watch run --urls=http://0.0.0.0:5000
   volumes:
     - ./backend:/app
   environment:
     - ASPNETCORE_ENVIRONMENT=Development
   ports:
     - "5000:5000"
 frontend:
   build:
     context: ./frontend
     dockerfile: Debug.Dockerfile
   command: npm run start
   volumes:
     - ./frontend:/app
     - /app/node_modules
   ports:
     - "4200:4200"
