version: '3.8'
services:
  backend:
    build:
      context: ./backend/src
      dockerfile: Debug.Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"  # For HTTPS if needed
    volumes:
      - ./backend:/app
      - backend-packages:/root/.nuget/packages  # Persist NuGet packages
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - AppSettings__ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=contacts;Username=contacts_admin;Password=YourStrongPassword123!
    depends_on:
      - postgres
    command: dotnet watch run --project Contact.Api/Contact.Api.csproj

  frontend:
    build:
      context: ./frontend
      dockerfile: Debug.Dockerfile
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend-packages:/app/node_modules
    command: npm run serve
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=contacts_admin
      - POSTGRES_PASSWORD=YourStrongPassword123!
      - POSTGRES_DB=contacts
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/scripts:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
  backend-packages:  # Persist NuGet packages
  frontend-packages:  # Persist node_modules
