version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspaces/app:cached
      - ../frontend/src/assets:/workspaces/app/frontend/src/assets:cached
    command: sleep infinity
    network_mode: service:postgres
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_ENVIRONMENT=Development
      - AppSettings__ConnectionStrings__DefaultConnection=Host=postgres;Database=contact_db;Username=postgres;Password=postgres

  postgres:
    build:
      context: ..
      dockerfile: .devcontainer/postgres.Dockerfile
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: contact_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ../backend/scripts:/docker-entrypoint-initdb.d
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres-data: